name: Setup Kotlin Toolchain
description: Set up JetBrains Kotlin Toolchain (Amper) with cross-platform caching for the toolchain, JDKs, and dependencies
author: RazerTexz
branding:
  icon: terminal
  color: purple

runs:
  using: composite
  steps:
    - name: Cache
      uses: actions/cache@v6
      with:
        path: |
          ~/.cache/JetBrains/Kotlin
          ~/Library/Caches/JetBrains/Kotlin
          ~/AppData/Local/JetBrains/Kotlin
        key: ${{ runner.os }}-kotlin-toolchain-${{ hashFiles('**/kotlin{,.bat}', '**/amper{,.bat}', '**/project.{yaml,yml}', '**/module.{yaml,yml}', '**/*.module-template.{yaml,yml}', '**/libs.versions.toml') }}
        restore-keys: ${{ runner.os }}-kotlin-toolchain-

    - name: Install (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        curl -fsSL https://kotl.in/install.sh | sh
        printf "%s\n" "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Install (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        irm https://kotl.in/install.ps1 | iex
        Add-Content -Path "$env:GITHUB_PATH" -Value "$HOME\.local\bin"