name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Kotlin Toolchain
        uses: ./

      - name: Test
        run: kotlin --version